name: Submodules Update Notification

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify updater of change
        run: |
          curl -X POST 'https://api.github.com/repos/ljakimczuk/config-test-updater/actions/workflows/trigger.yaml/dispatches' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.BOT_GITHUB_TOKEN }}' \
          -d '{"ref":"main"}'
